export const KEY_RANGE = [
  { natural: "q", flat: "1", sharp: "2" },
  { natural: "w", flat: "2", sharp: "3" },
  { natural: "e", flat: "3", sharp: "4" },
  { natural: "r", flat: "4", sharp: "5" },
  { natural: "t", flat: "5", sharp: "6" },
  { natural: "y", flat: "6", sharp: "7" },
  { natural: "u", flat: "7", sharp: "8" },
  { natural: "i", flat: "8", sharp: "9" },
  { natural: "o", flat: "9", sharp: "0" },
  { natural: "p", flat: "0", sharp: "-" },
  { natural: "[", flat: "-", sharp: "=" },
  { natural: "]", flat: "=", sharp: ";" },
  { natural: "z", flat: ";", sharp: "s" },
  { natural: "x", flat: "s", sharp: "d" },
  { natural: "c", flat: "d", sharp: "f" },
  { natural: "v", flat: "f", sharp: "g" },
  { natural: "b", flat: "g", sharp: "h" },
  { natural: "n", flat: "h", sharp: "j" },
  { natural: "m", flat: "j", sharp: "k" },
  { natural: ",", flat: "k", sharp: "l" },
  { natural: ".", flat: "l", sharp: "'" },
  { natural: "/", flat: "'" }
];

export const NOTE_TO_KEY = [
  ["C2", "Q"],
  ["C#2", "2"],
  ["D2", "W"],
  ["D#2", "3"],
  ["E2", "E"],
  ["F2", "R"],
  ["F#2", "5"],
  ["G2", "T"],
  ["G#2", "6"],
  ["A2", "Y"],
  ["A#2", "7"],
  ["B2", "U"],
  ["C3", "I"],
  ["C#3", "9"],
  ["D3", "O"],
  ["D#3", "0"],
  ["E3", "P"],
  ["F3", "["],
  ["F#3", "="],
  ["G3", "]"],
  ["G#3", ""],
  ["A3", "Z"],
  ["A#3", "S"],
  ["B3", "X"],

  ["C4", "C"],
  ["C#4", "F"],
  ["D4", "V"],
  ["D#4", "G"],
  ["E4", "B"],
  ["F4", "N"],
  ["F#4", "J"],
  ["G4", "M"],
  ["G#4", "K"],
  ["A4", ","],
  ["A#4", "L"],
  ["B4", "."],
  ["C5", "/"]
];
